language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
  - python: "3.7"
    dist: xenial
    sudo: true
install: pip install 'pytest >=3.0.0' 'distutils-pytest'
script: make test

# Local Variables:
# mode: yaml
# End:
