language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install 'pytest >=3.0.0' 'distutils-pytest'
script: make test

# Local Variables:
# mode: yaml
# End:
